eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,prometheus

wearhouse:
  s3:
    enabled: ${S3_ENABLED:false}
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_KEY:}
    region: ${S3_REGION:ap-northeast-2}
    bucket: ${S3_BUCKET:wearhouse-231629457117}
    public-base-url: ${S3_PUBLIC_BASE_URL:}
    presigned-put-expire-seconds: ${S3_PRESIGNED_PUT_EXPIRE_SECONDS:300}



#  ALTER USER 'wearhouse'@'localhost' IDENTIFIED BY 'm072715!';
#  ALTER USER 'wearhouse'@'%' IDENTIFIED BY 'm072715!';
#
#  GRANT ALL PRIVILEGES ON wearhouse_auth.*       TO 'wearhouse'@'localhost';
#  GRANT ALL PRIVILEGES ON wearhouse_user.*       TO 'wearhouse'@'localhost';
#  GRANT ALL PRIVILEGES ON wearhouse_product.*    TO 'wearhouse'@'localhost';
#  GRANT ALL PRIVILEGES ON wearhouse_order.*      TO 'wearhouse'@'localhost';
#  GRANT ALL PRIVILEGES ON wearhouse_payment.*    TO 'wearhouse'@'localhost';
#  GRANT ALL PRIVILEGES ON wearhouse_inventory.*  TO 'wearhouse'@'localhost';
#  GRANT ALL PRIVILEGES ON wearhouse_settlement.* TO 'wearhouse'@'localhost';
#
#  GRANT ALL PRIVILEGES ON wearhouse_auth.*       TO 'wearhouse'@'%';
#  GRANT ALL PRIVILEGES ON wearhouse_user.*       TO 'wearhouse'@'%';
#  GRANT ALL PRIVILEGES ON wearhouse_product.*    TO 'wearhouse'@'%';
#  GRANT ALL PRIVILEGES ON wearhouse_order.*      TO 'wearhouse'@'%';
#  GRANT ALL PRIVILEGES ON wearhouse_payment.*    TO 'wearhouse'@'%';
#  GRANT ALL PRIVILEGES ON wearhouse_inventory.*  TO 'wearhouse'@'%';
#  GRANT ALL PRIVILEGES ON wearhouse_settlement.* TO 'wearhouse'@'%';
#
#  FLUSH PRIVILEGES;
