wearhouse:
  product:
    image:
      key-prefix: ${PRODUCT_IMAGE_KEY_PREFIX:dev}
    passport:
      shared-secret: ${PASSPORT_SHARED_SECRET:wearhouse-passport-shared-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: product-service
