ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS item_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS shipping_fee DECIMAL(15,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS point_used_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(30) NULL,
    ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS recipient_phone VARCHAR(30) NULL,
    ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS address1 VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS address2 VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS delivery_request VARCHAR(255) NULL;
